// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    fileIndex,
    scanCheckpoints,
    sessions,
    operations,
    zoneOverrides,
    classificationRules,
    settings,
    fileIndexBySize,
    fileIndexByFullHash,
    operationsByTypeStatus,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 fileIndex = Shape1(
    source: i0.VersionedTable(
      entityName: 'file_index',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(source_id, path)'],
      columns: [
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 scanCheckpoints = Shape2(
    source: i0.VersionedTable(
      entityName: 'scan_checkpoints',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(source_id)'],
      columns: [_column_12, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 sessions = Shape3(
    source: i0.VersionedTable(
      entityName: 'sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 operations = Shape4(
    source: i0.VersionedTable(
      entityName: 'operations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(session_id, seq)'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_12,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_26,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 zoneOverrides = Shape5(
    source: i0.VersionedTable(
      entityName: 'zone_overrides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(source_id, folder)'],
      columns: [_column_12, _column_48, _column_49],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 classificationRules = Shape6(
    source: i0.VersionedTable(
      entityName: 'classification_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 settings = Shape7(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_56, _column_57],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index fileIndexBySize = i1.Index(
    'file_index_by_size',
    'CREATE INDEX file_index_by_size ON file_index (source_id, size)',
  );
  final i1.Index fileIndexByFullHash = i1.Index(
    'file_index_by_full_hash',
    'CREATE INDEX file_index_by_full_hash ON file_index (source_id, full_hash)',
  );
  final i1.Index operationsByTypeStatus = i1.Index(
    'operations_by_type_status',
    'CREATE INDEX operations_by_type_status ON operations (type, status, executed_at)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get canMove =>
      columnsByName['can_move']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get canMkdir =>
      columnsByName['can_mkdir']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get canQuarantine =>
      columnsByName['can_quarantine']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get quarantineRestorable =>
      columnsByName['quarantine_restorable']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get canAddToAlbum =>
      columnsByName['can_add_to_album']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get providesCapturedAt =>
      columnsByName['provides_captured_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get systemPurgesQuarantine =>
      columnsByName['system_purges_quarantine']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'can_move',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (can_move IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'can_mkdir',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (can_mkdir IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'can_quarantine',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (can_quarantine IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quarantine_restorable',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (quarantine_restorable IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'can_add_to_album',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (can_add_to_album IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'provides_captured_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (provides_captured_at IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'system_purges_quarantine',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (system_purges_quarantine IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (enabled IN (0, 1))',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get size =>
      columnsByName['size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get capturedAt =>
      columnsByName['captured_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get mimeType =>
      columnsByName['mime_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partialHash =>
      columnsByName['partial_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fullHash =>
      columnsByName['full_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastSeenScanId =>
      columnsByName['last_seen_scan_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'modified_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'captured_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime_type',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'partial_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'full_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_seen_scan_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scanId =>
      columnsByName['scan_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stage =>
      columnsByName['stage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cursor =>
      columnsByName['cursor']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scan_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stage',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cursor',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get finishedAt =>
      columnsByName['finished_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get statTotal =>
      columnsByName['stat_total']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get statDone =>
      columnsByName['stat_done']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get statFailed =>
      columnsByName['stat_failed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get statSkipped =>
      columnsByName['stat_skipped']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get statReverted =>
      columnsByName['stat_reverted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get statRevertSkipped =>
      columnsByName['stat_revert_skipped']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get statRemovedBytes =>
      columnsByName['stat_removed_bytes']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'finished_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stat_total',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stat_done',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stat_failed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stat_skipped',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stat_reverted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stat_revert_skipped',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stat_removed_bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get seq =>
      columnsByName['seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fromPath =>
      columnsByName['from_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get toPath =>
      columnsByName['to_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fingerprintSize =>
      columnsByName['fingerprint_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fingerprintModifiedAt =>
      columnsByName['fingerprint_modified_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fingerprintFullHash =>
      columnsByName['fingerprint_full_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quarantineRef =>
      columnsByName['quarantine_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reason =>
      columnsByName['reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupKey =>
      columnsByName['group_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get error =>
      columnsByName['error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get executedAt =>
      columnsByName['executed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get revertedAt =>
      columnsByName['reverted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'seq',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'from_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'to_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fingerprint_size',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fingerprint_modified_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fingerprint_full_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'quarantine_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reason',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'executed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reverted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get folder =>
      columnsByName['folder']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get zone =>
      columnsByName['zone']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'folder',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'zone',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get priority =>
      columnsByName['priority']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get extensions =>
      columnsByName['extensions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nameContains =>
      columnsByName['name_contains']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get folder =>
      columnsByName['folder']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'priority',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'extensions',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name_contains',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'folder',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
