// Generated by `dart run drift_dev make-migrations`, then filled in: the data
// integrity test checks what the v1 → v2 step does to stored rows.
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:file_organizer/core/model/model.dart';
import 'package:file_organizer/data/db/app_database.dart';
import 'package:file_organizer/data/repositories/drift_repositories.dart';
import 'package:flutter_test/flutter_test.dart';

import 'generated/schema.dart';
import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('simple database migrations', () {
    // Every schema update gives the schema of the target version.
    const versions = GeneratedHelper.versions;
    for (final (i, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(i + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final db = AppDatabase(schema.newConnection());
            await verifier.migrateAndValidate(db, toVersion);
            await db.close();
          });
        }
      });
    }
  });

  // Rows of schema version 1: free-text reasons and errors, no location.
  const oldSource = v1.SourcesData(
    id: 'home',
    kind: 'desktopFolder',
    displayName: 'Home',
    canMove: 1,
    canMkdir: 1,
    canQuarantine: 1,
    quarantineRestorable: 1,
    canAddToAlbum: 0,
    providesCapturedAt: 0,
    systemPurgesQuarantine: 0,
    enabled: 1,
  );
  const oldDone = v1.OperationsData(
    id: 'op1',
    sessionId: 's1',
    seq: 0,
    type: 'quarantine',
    sourceId: 'home',
    fromPath: 'Download/a (1).pdf',
    fingerprintSize: 3,
    fingerprintModifiedAt: 1704067200000000,
    quarantineRef: 'q/1',
    reason: 'duplicate of Download/a.pdf',
    groupKey: 'duplicates',
    status: 'done',
    executedAt: 1704067201000000,
  );
  const oldSkipped = v1.OperationsData(
    id: 'op2',
    sessionId: 's1',
    seq: 1,
    type: 'move',
    sourceId: 'home',
    fromPath: 'Download/b.txt',
    toPath: 'Документы/b.txt',
    fingerprintSize: 5,
    fingerprintModifiedAt: 1704067200000000,
    reason: 'extension .txt',
    groupKey: 'move:Документы',
    status: 'skipped',
    error: 'file changed since the scan',
    executedAt: 1704067202000000,
  );
  const oldSetting = v1.SettingsData(
    key: 'quarantine_retention_us',
    value: '604800000000',
  );

  test('migration from v1 to v2 keeps the data and wraps old texts', () async {
    await verifier.testWithDataIntegrity(
      oldVersion: 1,
      newVersion: 2,
      createOld: v1.DatabaseAtV1.new,
      createNew: v2.DatabaseAtV2.new,
      openTestedDatabase: AppDatabase.new,
      createItems: (batch, oldDb) {
        batch
          ..insert(oldDb.sources, oldSource)
          ..insertAll(oldDb.operations, [oldDone, oldSkipped])
          ..insert(oldDb.settings, oldSetting);
      },
      validateItems: (newDb) async {
        expect(await newDb.select(newDb.sources).get(), [
          const v2.SourcesData(
            id: 'home',
            kind: 'desktopFolder',
            displayName: 'Home',
            location: '',
            canMove: 1,
            canMkdir: 1,
            canQuarantine: 1,
            quarantineRestorable: 1,
            canAddToAlbum: 0,
            providesCapturedAt: 0,
            systemPurgesQuarantine: 0,
            enabled: 1,
          ),
        ]);
        final ops = await (newDb.select(
          newDb.operations,
        )..orderBy([(t) => OrderingTerm(expression: t.seq)])).get();
        expect(ops.map((o) => (o.reason, o.error)), [
          ('{"code":"legacy","text":"duplicate of Download/a.pdf"}', null),
          (
            '{"code":"legacy","text":"extension .txt"}',
            '{"code":"legacy","text":"file changed since the scan"}',
          ),
        ]);
        expect(ops.map((o) => (o.id, o.status, o.toPath, o.quarantineRef)), [
          ('op1', 'done', null, 'q/1'),
          ('op2', 'skipped', 'Документы/b.txt', null),
        ]);
        expect(await newDb.select(newDb.settings).get(), [
          const v2.SettingsData(
            key: 'quarantine_retention_us',
            value: '604800000000',
          ),
        ]);
      },
    );
  });

  test('the repositories read migrated rows as legacy codes', () async {
    final schema = await verifier.schemaAt(1);
    final old = v1.DatabaseAtV1(schema.newConnection());
    await old.batch((batch) {
      batch
        ..insert(old.sources, oldSource)
        ..insertAll(old.operations, [oldDone, oldSkipped]);
    });
    await old.close();

    final db = AppDatabase(schema.newConnection());
    addTearDown(db.close);
    final source = await DriftSourceRepository(db).byId(const SourceId('home'));
    expect(source!.location, '');
    final ops = await DriftOperationJournal(db)
        .bySession(const SessionId('s1'));
    expect(ops.map((o) => o.reason), const [
      LegacyReason('duplicate of Download/a.pdf'),
      LegacyReason('extension .txt'),
    ]);
    expect(ops.map((o) => o.error), const [
      null,
      LegacyProblem('file changed since the scan'),
    ]);
  });
}
