// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.brobrocode.file_organizer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * What the progress notification of the foreground service shows. The
 * texts come from the app's localization.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ForegroundNotice (
  val title: String,
  val text: String,
  /** Name of the notification channel in the system settings. */
  val channelName: String,
  /** Progress: [done] of [total]; `total == 0` shows an indeterminate bar. */
  val done: Long,
  val total: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ForegroundNotice {
      val title = pigeonVar_list[0] as String
      val text = pigeonVar_list[1] as String
      val channelName = pigeonVar_list[2] as String
      val done = pigeonVar_list[3] as Long
      val total = pigeonVar_list[4] as Long
      return ForegroundNotice(title, text, channelName, done, total)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      text,
      channelName,
      done,
      total,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ForegroundNotice
    return NativeApiPigeonUtils.deepEquals(this.title, other.title) && NativeApiPigeonUtils.deepEquals(this.text, other.text) && NativeApiPigeonUtils.deepEquals(this.channelName, other.channelName) && NativeApiPigeonUtils.deepEquals(this.done, other.done) && NativeApiPigeonUtils.deepEquals(this.total, other.total)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeApiPigeonUtils.deepHash(this.title)
    result = 31 * result + NativeApiPigeonUtils.deepHash(this.text)
    result = 31 * result + NativeApiPigeonUtils.deepHash(this.channelName)
    result = 31 * result + NativeApiPigeonUtils.deepHash(this.done)
    result = 31 * result + NativeApiPigeonUtils.deepHash(this.total)
    return result
  }
  override fun toString(): String {
    return "ForegroundNotice(title=$title, text=$text, channelName=$channelName, done=$done, total=$total)"
  }
}
private open class NativeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ForegroundNotice.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ForegroundNotice -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * "All files access" and the notification permission. Runs on the main
 * thread: the requests need the activity.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AccessApi {
  fun hasAllFilesAccess(): Boolean
  /**
   * Opens the system screen "All files access" for the app and answers
   * when the user comes back: whether access is granted then. Answers at
   * once, without the screen, if access is already granted.
   */
  fun requestAllFilesAccess(callback: (Result<Boolean>) -> Unit)
  /**
   * Whether the app may post notifications (Android 13+ runtime
   * permission, and notifications not turned off for the app).
   */
  fun hasNotificationPermission(): Boolean
  /**
   * Shows the system dialog (Android 13+) and answers with the result.
   * Answers at once if the permission is already granted, and on older
   * versions.
   */
  fun requestNotificationPermission(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by AccessApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
    /** Sets up an instance of `AccessApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AccessApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.AccessApi.hasAllFilesAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasAllFilesAccess())
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.AccessApi.requestAllFilesAccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestAllFilesAccess{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.AccessApi.hasNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasNotificationPermission())
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.AccessApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestNotificationPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Shared storage. Runs on a background thread.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface StorageApi {
  /**
   * The root of the primary shared storage (`/storage/emulated/0`), or
   * `null` if it is not mounted.
   */
  fun primaryStorageRoot(): String?
  /**
   * `DATE_TAKEN` of MediaStore, in milliseconds since the epoch (UTC), for
   * the files at the absolute [paths]. Files without a capture date (not
   * media, not indexed) are missing from the answer.
   */
  fun capturedDates(paths: List<String>): Map<String, Long>

  companion object {
    /** The codec used by StorageApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
    /** Sets up an instance of `StorageApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StorageApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.StorageApi.primaryStorageRoot$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.primaryStorageRoot())
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.StorageApi.capturedDates$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathsArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.capturedDates(pathsArg))
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * The foreground service (type `dataSync`) that keeps a scan, cleanup or
 * undo running while the app is in the background.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ForegroundApi {
  /** Starts the service with its notification, or updates it if it runs. */
  fun start(notice: ForegroundNotice)
  /**
   * Updates the notification. Throttled to a few updates per second; the
   * last one is always shown.
   */
  fun update(notice: ForegroundNotice)
  /** Stops the service and removes the notification. */
  fun stop()
  fun isRunning(): Boolean
  /**
   * What the notification shows now (read back from the system), or
   * `null` if there is none.
   */
  fun currentNotice(): ForegroundNotice?

  companion object {
    /** The codec used by ForegroundApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
    /** Sets up an instance of `ForegroundApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ForegroundApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.ForegroundApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val noticeArg = args[0] as ForegroundNotice
            val wrapped: List<Any?> = try {
              api.start(noticeArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.ForegroundApi.update$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val noticeArg = args[0] as ForegroundNotice
            val wrapped: List<Any?> = try {
              api.update(noticeArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.ForegroundApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.ForegroundApi.isRunning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isRunning())
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.file_organizer.ForegroundApi.currentNotice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.currentNotice())
            } catch (exception: Throwable) {
              NativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Calls from the service to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class ForegroundEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ForegroundEvents. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
  }
  /**
   * The system stopped the service: the `dataSync` time limit of Android
   * 15+ ran out. The work in progress should be cancelled.
   */
  fun onTimeout(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.file_organizer.ForegroundEvents.onTimeout$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(NativeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
